ifeq ($(TARGET_FSL_IMX_2D),DPU2D)
LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libg2d
LOCAL_MODULE_SUFFIX :=.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
ifdef TARGET_2ND_ARCH
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_64 := lib64/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH_64 := $(TARGET_OUT)/lib64/
LOCAL_SRC_FILES_32 := lib/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH_32 := $(TARGET_OUT)/lib/
else
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)$(LOCAL_MODULE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib/
endif
include $(BUILD_PREBUILT)
endif
